[context.production.environment]
    REDIS_PREFIX = "prod"

[context.develop.environment]
    REDIS_PREFIX = "develop"

[context.deploy-preview.environment]
    REDIS_PREFIX = "deploy-preview"

[context.branch-deploy.environment]
    REDIS_PREFIX = "feature-branch"

    